### ISSUE TITLE
README sample code doesn't work, 'receipt' should be 'result'

### ISSUE THREAD

**Issue by grempe** [chainpoint/chainpoint-validate-js#1]
In your README sample code you provide commented example code like the following in the callback handler:

```
chainpointValidate.isValidReceipt(validReceipt, true, function (err, result) {
  if(err) {
    // handle this error
  } else {
    // receipt.isValid will equal true
    // receipt.anchors will be an array of anchor objects, optionally including
    // an exists parameter, if you configured validation to confirm the anchor as well
  }
});
```

The object available in the callback for these examples is `result`, not `receipt`

Also, since you include a sample valid receipt below this in the README, I would suggest making the sample code full copy-paste'able.  Include both a valid receipt, and an invalid receipt in the sample and have it run both.

**Comment by jasonbukowski** [comment]
I've corrected the error in the comments, and added valid receipt data for the 'validReceipt' variable. The 'invalidReceipt' variable already contains a value which is invalid. If you had more substantive changes in mind, send a pull request, I'm open to whatever suggestions you may have.

**Comment by grempe** [comment]
Looks good! Thx
