### ISSUE TITLE
3.x update roadmap

### ISSUE THREAD

**Issue by pellicceama** [chainpoint/chainpoint-validate-js#3]
Hi, 

Are there plans to upgrade this library to support versions >= 3? It's a little bit tedious having to run a node or call an external service (like you API) to make local validations. Thanks!

**Comment by grempe** [comment]
Hello, and thanks for the feedback. We provide other libraries that can perform all validation of a Chainpoint v3 proof. This validation can also be done completely locally with only access to a Bitcoin block explorer if desired (not required to validate against a Tierion server or Node).

I suggest taking a look at these two runkit examples which demonstrate this.

https://runkit.com/tierion

Cheers
